# This file provides instructions for packaging.

@prefix : <http://purl.org/NET/cpan-uri/terms#> .

<http://purl.org/NET/cpan-uri/dist/JSON-Schema/project>
	:perl_version_from _:main ;
	:version_from _:main ;
	:readme_from _:main ;
	:test_requires "Test::More 0.94" ;
	:requires
		"autovivification 0",
		"HTTP::Link::Parser 0.100" ,
		"JSON 2.00" ,
		"JSON::Hyper 0" ,
		"JSON::Path 0" ,
		"LWP::UserAgent 0" .

_:main <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileName> "lib/JSON/Schema.pm" .

